### PR TITLE
Added Python_basics

### PR DESCRIPTION
**Pull request by keivalya**
I created this notebook with the help of different resources.
A very small notebook consisting of 6 extremely beginner-friendly blocks of code.
This notebook intends to create curiosity amongst newbies and get them started with PANDAS!

Hope you approve my changes.
Happy learning to you!

### CODE REVIEW

**Comment by achoudh5** [comment]
Hi @keivalya 

Are all the 6 codes in a single file that is `Python_basics.py` ? If yes, I would like you to split them with a one line problem statement at top of each file. Also, please make a folder like `Python basics` and add these codes there, it'll keep the repo clean :)

**Comment by keivalya** [comment]
Yes, @achoudh5 every code is in the same file.
However, to keep it clean, I've separated them with small blocks of texts which are some-what like problems. They also intend to explain basic concepts.
I also understand your concern regarding keeping repo clean. I definitely admire that!
I'll make changes regarding the folder.
I've already made sure to keep the Notebook as clean as possible. You won't find any difficulty in there. I assure you!

And still, if you need ANY further changes, I'll be happy to do them.😄

**Comment by achoudh5** [comment]
hmm, when I glanced at your file I couldn't figure out the questions. Can you put a comment in between continuous code lines?

**Comment by keivalya** [comment]
Yes! In that case, @achoudh5 For sure, I'll make the changes.
Thanks for letting me know.
I'll be creating my PR within an hour.

**Pull request closed without merging**
