### PR TITLE
added a src folder containing 2 tutorials and a readme file

### PR DESCRIPTION
**Pull request by syedzubeen**
added a src folder to store basic tutorial scripts related to pandas
added two tutorials and a readme file to contribute to the folder along with naming conventions

### CODE REVIEW

**Review by achoudh5 — COMMENTED** [review]
Hi @syedzubeen 

Thank you for your contribution, everything seems to be perfect but can you make a FAQ folder and just put a hyperlink of that folder on readme instead? I want readme to be shorter if it makes sense :)

**Comment by syedzubeen** [comment]
done @achoudh5

**Comment by achoudh5** [comment]
Reviewing...

**Comment by achoudh5** [comment]
Thank you for your contribution @syedzubeen  !

**Pull request merged**
